#!/usr/bin/python

import argparse
import readline
import rlcompleter
import sys

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='Help users focus on Baekjoon.', usage=f"{sys.argv[0]} (command) (id) [option]")
    subparsers = parser.add_subparsers(
        dest='command', required=True, metavar="command")

    parser_make = subparsers.add_parser(
        'make', help='Make new problem dir', usage="%(prog)s (id) [option]", prog=" ".join(sys.argv[:-1]))
    parser_make.add_argument("pro_num", help="Problem number", metavar="id")
    parser_make.add_argument(
        "-f", "--force", help="Make force", action="store_true", dest="force")

    parser_run = subparsers.add_parser(
        'run', help="문제 정답을 컴파일 합니다.", usage="%(prog)s (id) [option]", prog=" ".join(sys.argv[:-1]))
    parser_run.add_argument("pro_num", help="Problem number", metavar="id")
    parser_run.add_argument(
        "-f", "--name", help="파일 이름 지정(경로 아님)", action="store", dest="name")
    parser_run.add_argument(
        "-c", "--no-check", help="정답을 확인하지 않음", action="store_true", dest="noCheck")
    parser_run.add_argument(
        "-o", "--one", help="첫 번째 input만 테스트함", action="store_true", dest="one")
    parser_run.add_argument(
        "-r", "--repeat", help="파일이 변경 될 때 마다 반복", action="store_true", dest="repeat")

    args = parser.parse_args()

    command = args.command
    if command == "make":
        from liboj import MakeBoj
        MakeBoj(args=args)
    elif command == "run":
        from liboj import RunBoj
        RunBoj(args=args)
