#!/usr/bin/python

import argparse
import readline
import rlcompleter

if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description='Help users focus on Baekjoon.', epilog="파이썬에서 이게 되네 ㅋㅋ")
    subparsers = parser.add_subparsers(dest='command', required=True)

    parser_make = subparsers.add_parser('make', help='Make new problem dir', usage="%(prog)s (id) [option]")
    parser_make.add_argument("-f", "--force", help="Make force", action="store_true", dest="force")
    parser_make.add_argument("pro_num", help="Problem number", metavar="id")

    parser_run = subparsers.add_parser('run', help="추후 개발 예정")

    args = parser.parse_args()

    command = args.command
    if command == "make":
        from liboj import MakeBoj
        MakeBoj(args=args)
    elif command == "run":
        pass